### ISSUE TITLE
Question regarding GMVAE code

### ISSUE THREAD

**Issue by aayushARM** [jariasf/GMVAE#2]
Hi @jariasf ,
Thanks for the code, first of all. I was wondering, does the GMVAE model definition in your repo here: https://github.com/jariasf/GMVAE/blob/master/pytorch/networks/Networks.py
essentially implement the "Real Gaussian Mixture VAE" as described in this blog post?: http://ruishu.io/2016/12/25/gmvae/
It seems so, but the readme.md doesn't explicitly say that, so I wanted to confirm.

Thanks in advance!

**Comment by jariasf** [comment]
HI @aayushARM,

You are right, thanks for letting me know. I have updated the README.
